name: CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4.2.2

      - name: Set Up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Show contents of the current working directory
        run: ls -la
        
      - name: Show contents of the target directory
        run: ls -la target
